### ISSUE TITLE
SVG style output

### ISSUE THREAD

**Issue by klokan** [mnboos/mapbox-gl-style-to-qgis#1]
Would it be technically doable to reuse part of your parsing and generating styling code to write SVG styling language too - to get from Mapbox GL JSON language into SVG?
https://www.w3.org/TR/SVG/styling.html

It would be probably a fork of your code, then right?

What would be estimated effort @mnboos?

I am thinking of a bit advanced version of http://hanshack.com/mapxtract/ (with code at
https://github.com/openmaptiles/mapxtract)

which is using our map tiles.

**Comment by mnboos** [comment]
Parts of it could be reused I think, as the QML files are just XML. If you are in a javascript environment, that would also solve the question of how to control the visibility of features depending on the properties and/or map-scale.

The effort strongly depends on the amount of features to implement from the Mapbox Style spec. This converter here is far from complete.

**Comment by klokan** [comment]
Thanks for answering!

QGIS supports export into SVG and vector PDF - for the styles which are loaded.

It means the code for QML to SVG exists already - if you make this glstyle2qgis converter well - people could generate vector PDFs and SVGs from the vector tile maps right now!

Pretty cool...
